[features]
seeds = false
skip-lint = false

[programs.localnet]
gor_race = "2Xov1MEbY8DdK3MDci83RDJmAK1SHJxg4HtoiCLcBUen"

[programs.testnet]
gor_race = "2Xov1MEbY8DdK3MDci83RDJmAK1SHJxg4HtoiCLcBUen"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.gorbagana.wtf"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://rpc.gorbagana.wtf"

[toolchain]
anchor_version = "0.29.0"

[workspace]
members = ["programs/gor-race/"]